version: '2'
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: testing
    opensearch-node1:
        image: opensearchproject/opensearch:2.1.0
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node1
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - "DISABLE_INSTALL_DEMO_CONFIG=true"
            - "DISABLE_SECURITY_PLUGIN=true"
            - "discovery.type=single-node"
    server:
        image: ubuntu:22.04
        volumes:
            - ./server/target/debug/server:/server:ro
        command: /server
    proxy:
        image: caddy
        volumes:
            - ./packages/polycentric-web/build:/static:ro
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - ./state/caddy/data:/data
            - ./state/caddy/config:/config
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"

