version: '2'
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: testing
    opensearch-node1:
        image: opensearchproject/opensearch:2.1.0
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node1
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - "DISABLE_INSTALL_DEMO_CONFIG=true"
            - "DISABLE_SECURITY_PLUGIN=true"
            - "discovery.type=single-node"
    opensearch-dashboards:
        image: opensearchproject/opensearch-dashboards:2.1.0
        ports:
            - "127.0.0.1:5601:5601"
        environment:
            - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
            - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    development:
        build:
            context: ./
            dockerfile: Dockerfile
        read_only: true
        working_dir: /app
        environment:
            HOME: "/tmp/home"
        user: "${CURRENT_UID}:${CURRENT_GID}"
        volumes:
            - ./:/app
        tmpfs:
            - /tmp:exec
        ports:
            - "127.0.0.1:3000:3000"
            - "127.0.0.1:8081:8081"
        cap_add:
            - SYS_ADMIN
        command: tail -F wait_forever
